### PR TITLE
Backporting fail stream to 0.9

### PR DESCRIPTION
**Pull request by stanlemon**
Attempts to splice #90 onto the 0.9 branch.

If we can make this work we'll cut a 0.9.3 of this for @danielsd & friends.

### CODE REVIEW

**Comment by Crim** [comment]
Should I review this PR or the other PR?

**Comment by stanlemon** [comment]
@Crim this one.

**Comment by Crim** [comment]
You got weird error msgs in your test logs:

> java.io.IOException: java.net.UnknownHostException: localhost2

> 20:41:47.249 WARN  o.a.k.c.NetworkClient [DynamicSpout:main]: Connection to node 1 could not be established. Broker may not be available.


Whats up w/ the failing test?

**Comment by stanlemon** [comment]
@Crim Unfortunately this was not a simple grafting of the changeset onto 0.9. That test is completely different in 0.10. We dropped Kafka from it and made a bunch of other changes. I did my best to get it to a point where it could compile, but this is basically what I need to focus on. Hoping to dig in more tomorrow.

**Comment by stanlemon** [comment]
@Crim build is passing now, can I get a review?

**Pull request merged**
